# Generated by Django 3.1 on 2022-07-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0002_auto_20220712_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
    ]
