# Generated by Django 3.1 on 2022-07-16 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0003_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
