# Generated by Django 3.1 on 2022-07-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0013_auto_20220719_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='num_following',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='_profile_followers_+', to='twitter_app.Profile'),
        ),
    ]
